#!/usr/bin/env bash

# build the docs
cd docs
make clean
make html
cd ..

# commit and push
git add -A
git commit -m "building and pushing docs"
git push gh master

# switch branches and pull the data we want
git checkout gh-pages
# rm -rf .
rm README.me
touch .nojekyll
git checkout master docs/build/html
rm -rf _static _sources _modules
mv ./docs/build/html/* ./
rm -rf ./docs
git add -A
git commit -m "publishing updated docs..."
git push gh gh-pages

# switch back
git checkout master
